#!/usr/bin/env bash
# script to configure the hosts file

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/etc/hosts.new /etc/hosts

